drop procedure change_entity    ( IN _cid integer, IN _entity json                                  );
drop procedure change_entity    ( IN _cid integer, IN _entity json, IN _max_oid integer             );
drop procedure change_link      ( IN _cid integer, IN _link json                                    );
drop procedure change_link      ( IN _cid integer, IN _link jsonb                                   );
drop procedure change_link      ( IN _cid integer, IN _link json, IN _max_oid integer               );
drop procedure change_link      ( IN _cid integer, IN _link record                                  );
drop procedure change_link      ( IN _cid integer, IN _oid integer, IN _rid integer, IN _link json, IN _max_oid integer                                                                      );
drop procedure change_link      ( IN _cid integer, IN _oid integer, IN _src_oid integer, IN _src_rid integer, IN _trgt_oid integer, IN _trgt_rid integer, IN _name text, IN _deleted boolean );
drop procedure change_vobject   ( IN _cid integer, IN _oid integer                                  );
drop procedure change_vobject   ( IN _cid integer, IN _revision json                                );
drop procedure change_vobject   ( IN _cid integer, IN _revision json, IN _max_oid integer           );
drop function checkout_links  ; 
drop function checkout_vobject ;
drop procedure initialize       (                                                                   );
drop procedure new_changeset    ( IN _author text, IN _comment text, IN _entities json, OUT _max_oid integer                                                                                 );
drop procedure new_changeset    ( IN _comment text, IN _entities jsonb, OUT _max_oid integer        );
drop procedure new_changeset    ( IN _comment text, IN _entities json, OUT _max_oid integer         );
drop procedure new_changeset    ( IN _revisions json, IN _links json                                );
drop procedure new_root         ( IN _oid integer, IN _name text                                    );
drop procedure change_entity    ( IN _cid integer, IN _entity json                                  );
drop procedure change_entity    ( IN _cid integer, IN _entity json, IN _max_oid integer             );
drop procedure change_link      ( IN _cid integer, IN _link json                                    );
drop procedure change_link      ( IN _cid integer, IN _link jsonb                                   );
drop procedure change_link      ( IN _cid integer, IN _link json, IN _max_oid integer               );
drop procedure change_link      ( IN _cid integer, IN _link record                                  );
drop procedure change_link      ( IN _cid integer, IN _oid integer, IN _rid integer, IN _link json, IN _max_oid integer                                                                      );
drop procedure change_link      ( IN _cid integer, IN _oid integer, IN _src_oid integer, IN _src_rid integer, IN _trgt_oid integer, IN _trgt_rid integer, IN _name text, IN _deleted boolean );
drop procedure change_vobject   ( IN _cid integer, IN _oid integer                                  );
drop procedure change_vobject   ( IN _cid integer, IN _revision json                                );
drop procedure change_vobject   ( IN _cid integer, IN _revision json, IN _max_oid integer           );
drop procedure checkout_links   ;
drop procedure initialize       (                                                                   );
drop procedure new_changeset    ( IN _author text, IN _comment text, IN _entities json, OUT _max_oid integer                                                                                 );
drop procedure new_changeset    ( IN _comment text, IN _entities jsonb, OUT _max_oid integer        );
drop procedure new_changeset    ( IN _comment text, IN _entities json, OUT _max_oid integer         );
drop procedure new_changeset    ( IN _revisions json, IN _links json                                );
drop procedure new_root         ( IN _oid integer, IN _name text                                    );
