
CREATE ROLE archivist ;
CREATE ROLE curator WITH CREATEDB CREATEROLE;

GRANT SELECT, INSERT, DELETE, UPDATE ON ALL TABLES IN SCHEMA public TO archivist;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA public TO archivist;

GRANT archivist TO curator;

